# Generated by Django 3.1.5 on 2021-01-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
