# Generated by Django 3.1.5 on 2021-01-21 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0002_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 1, 21, 20, 8, 51, 655615, tzinfo=utc)),
        ),
    ]
